again

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,47 +1,139 @@
-# Main Travis CI configuration file for wordpress-plugin tests
-# https://github.com/benbalter/wordpress-plugin-tests
-
-# Tell Travis CI we're using PHP
 language: php
+dist: trusty
+sudo: false
 
-# Versions of PHP to test against
-php:
-  - "7.0"
-  - "5.6"
-  - "5.5"
-  - "5.4"
-  - "5.3"
-  # Current $required_php_version for WordPress: 5.2.4
-  - "5.2"
-  
-# Specify versions of WordPress to test against
-# WP_VERSION = WordPress version number (use "master" for SVN trunk)
-# WP_MULTISITE = whether to test multisite (use either "0" or "1")
-env:
-    - WP_VERSION=master WP_MULTISITE=0
-    - WP_VERSION=3.4.1 WP_MULTISITE=0
-    - WP_VERSION=3.3.2 WP_MULTISITE=0
-    - WP_VERSION=3.2.1 WP_MULTISITE=0 
-    - WP_VERSION=master WP_MULTISITE=1
-    - WP_VERSION=3.4.1 WP_MULTISITE=1
-    - WP_VERSION=3.3.2 WP_MULTISITE=1 
-    - WP_VERSION=3.2.1 WP_MULTISITE=1
+jobs:
+  fast_finish: true
+  include:
+    - php: 7.2
+      env: WP_VERSION=4.9 WP_MULTISITE=1 PHPLINT=1 PHPCS=1 CHECKJS=1 TRAVIS_NODE_VERSION=node
+    - php: 7.2
+      env: WP_VERSION=4.9 WP_MULTISITE=1 COVERAGE=1
+    - php: 5.2
+      # As 'trusty' is not supporting PHP 5.2/5.3 anymore, we need to force using 'precise'.
+      dist: precise
+      env: WP_VERSION=4.8 WP_MULTISITE=1 PHPLINT=1
+    - php: 5.3
+      # As 'trusty' is not supporting PHP 5.2/5.3 anymore, we need to force using 'precise'.
+      dist: precise
+      env: WP_VERSION=4.9
+    - php: 5.6
+      env: WP_VERSION=4.9
+    # WP >= 4.8 is needed for PHP 7.1
+    - php: 7.0
+      env: WP_VERSION=4.9
+    - php: 5.2
+      # As 'trusty' is not supporting PHP 5.2/5.3 anymore, we need to force using 'precise'.
+      dist: precise
+      env: WP_VERSION=master
+    - php: nightly
+      env: WP_VERSION=master
+    
+  allow_failures:
+    # Allow failures for unstable builds.
+    - php: nightly
+    - env: WP_VERSION=master
 
-# Grab the setup script and execute
+cache:
+  yarn: true
+  directories:
+    - vendor
+    - $HOME/.composer/cache
+    - node_modules
+
+before_install:
+- if [[ -z "$CC_TEST_REPORTER_ID" ]]; then COVERAGE="0"; fi
+- if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
+- |
+  if [[ "$CHECKJS" == "1" ]]; then
+    nvm install $TRAVIS_NODE_VERSION
+    curl -o- -L https://yarnpkg.com/install.sh | bash
+    export PATH=$HOME/.yarn/bin:$PATH
+  fi
+install:
+- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local 5.6.13; fi
+- if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then composer require --dev phpunit/phpunit ^5.7; fi
+- composer install --no-interaction
+- composer config-yoastcs
+- if [[ $TRAVIS_PHP_VERSION == "5.2" || $TRAVIS_PHP_VERSION == "5.3" ]]; then phpenv local --unset; fi
+- |
+  if [[ "$CHECKJS" == "1" ]]; then
+    yarn global add grunt-cli
+    yarn install
+  fi
 before_script:
-    - wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
-    - source setup.sh
+- PLUGIN_SLUG=$(basename $(pwd))
+- export WP_DEVELOP_DIR=/tmp/wordpress/
+- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
+- cd ..
+- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
+- cd /tmp/wordpress/
+- cp wp-tests-config-sample.php wp-tests-config.php
+- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
+- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
+- sed -i "s/yourpasswordhere//" wp-tests-config.php
+- mysql -e "CREATE DATABASE wordpress_tests;" -uroot
+- cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
+- phpenv rehash
+- |
+  if [[ "$COVERAGE" == "1" ]]; then
+    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+    chmod +x ./cc-test-reporter
+    ./cc-test-reporter before-build
+  fi
+- export -f travis_fold
+- export -f travis_time_start
+- export -f travis_time_finish
 
-  - composer global require wp-coding-standards/wpcs
-  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
-script: phpunit
-  - phpcbf .
-  - phpcs .
-  #- phpcs --standard=WordPress .
-  - phpcs -p -s -v -n --standard=WordPress .
+script:
+# JavaScript checks
+- |
+  if [[ "$CHECKJS" == "1" ]]; then
+    travis_fold start "JavaScript.check" && travis_time_start
+    grunt check:js
+    travis_time_finish && travis_fold end "JavaScript.check"
+  fi
+# JavaScript tests
+- |
+  if [[ "$CHECKJS" == "1" ]]; then
+    travis_fold start "JavaScript.tests" && travis_time_start
+    yarn test
+    travis_time_finish && travis_fold end "JavaScript.tests"
+  fi
+# PHP Linting
+- |
+  if [[ "$PHPLINT" == "1" ]]; then
+    travis_fold start "PHP.check" && travis_time_start
+    find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
+    travis_time_finish && travis_fold end "PHP.check"
+  fi
+# PHP CS
+- |
+  if [[ "$PHPCS" == "1" ]]; then
+    travis_fold start "PHP.code-style" && travis_time_start
+    vendor/bin/phpcs -q --runtime-set ignore_warnings_on_exit 1
+    travis_time_finish && travis_fold end "PHP.code-style"
+  fi
+# PHP Unit
+- |
+  if [[ "$COVERAGE" != "1" ]]; then
+    travis_fold start "PHP.tests" && travis_time_start
+    if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then phpunit -c phpunit.xml; fi
+    if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then vendor/bin/phpunit -c phpunit.xml; fi
+    travis_time_finish && travis_fold end "PHP.tests"
+  fi;
+# Coverage environment variable is only set on the PHP 7 build, so we can safely
+# assume that PHPUnit is in the vendor directory.
+- |
+  if [[ "$COVERAGE" == "1" ]]; then
+    travis_fold start "PHP.coverage" && travis_time_start
+    vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
+    travis_time_finish && travis_fold end "PHP.coverage"
+  fi
+# Validate the composer.json file.
+# @link https://getcomposer.org/doc/03-cli.md#validate
+- if [[ $TRAVIS_PHP_VERSION == "5.3" || $TRAVIS_PHP_VERSION == "7.2" ]]; then composer validate --no-check-all; fi
 
-# wordpress-plugin-tests specific config
-# Tells Travis CI not to run unit tests against the setup branch
-branches:
-  except:
-    - setup
+after_script:
+  - if [[ "$COVERAGE" == "1" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
+
